### ISSUE TITLE
Wrong twig functions names with clean installation.

### ISSUE THREAD

**Issue by namaless** [getherbie/start-website#2]
I give this error after clean installation:
<code>Twig_Error_Syntax: The function "pageTitle" does not exist. Did you mean "pagetitle" in "main.html" at line 16</code>
I think you missed to change the twig function with new name version.

**Comment by namaless** [comment]
<code>Twig_Error_Syntax: The function "bodyClass" does not exist. Did you mean "bodyclass" in "main.html" at line 26</code>

**Comment by tbreuss** [comment]
Thank you for reporting! This is fixed with 6edf4ad01fa1b41a7283772c7cdc72f3d49e32fe
