### ISSUE TITLE
Missed site folders

### ISSUE THREAD

**Issue by namaless** [getherbie/start-website#4]
With adminpanel get error because this folder not exists. I think we can add into the base project for remove this issue for the new users.

**Comment by namaless** [comment]
The same for the posts folder, so we need to add:
- site/data
- site/posts

thanks

**Comment by tbreuss** [comment]
Thank you for reporting this issue. It is fixed with 8a4f84e7e3aee98e81b932e86fabf063c058cee3.

**Comment by tbreuss** [comment]
Thank you for reporting this issues. They are fixed with https://github.com/getherbie/start-website/commit/8a4f84e7e3aee98e81b932e86fabf063c058cee3.
